[package]
name = "quake-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-model = { path = "../quake-model" }

anyhow.workspace = true
glam.workspace = true
pollster.workspace = true
wgpu.workspace = true

raw-window-handle = "0.6.2"
encase = "0.12.0"
bytemuck = "1.24.0"
