[package]
name = "quake-model"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-collision = { path = "../quake-collision" }
quake-pack = { path = "../quake-pack" }

byteorder = "1.5.0"
anyhow = "1.0.100"
bitflags = "2.10.0"
glam = "0.30.8"
