[package]
name = "quake-model"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-collision = { path = "../quake-collision" }
quake-resource = { path = "../quake-resource" }

anyhow.workspace = true
byteorder.workspace = true
glam.workspace = true

bitflags = "2.10.0"
