[package]
name = "quake-app"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-animation = { path = "../quake-animation" }
quake-console = { path = "../quake-console" }
quake-model = { path = "../quake-model" }
quake-resource = { path = "../quake-resource" }
anyhow = "1.0.100"
