[package]
name = "quake-app"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-console = { path = "../quake-console" }
quake-input = { path = "../quake-input" }
quake-resource = { path = "../quake-resource" }

anyhow = "1.0.100"
