[package]
name = "quake-app"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-animation = { path = "../quake-animation" }
quake-command = { path = "../quake-command" }
quake-model = { path = "../quake-model" }
quake-resource = { path = "../quake-resource" }
