pub mod builtins;
pub mod client;
pub mod server;

mod dem;

const CONNECTION_CONTROL_REQUEST: u8 = 0x01;
const SERVER_INFO_CONTROL_REQUEST: u8 = 0x02;
const PLAYER_INFO_CONTROL_REQUEST: u8 = 0x03;
const RULE_INFO_CONTROL_REQUEST: u8 = 0x04;
const ACCEPT_CONNECTION_CONTROL_RESPONSE: u8 = 0x81;
const REJECT_CONNECTION_CONTROL_RESPONSE: u8 = 0x82;

const DISCONNECT_CLIENT_REQUEST: u8 = 0x02;
