[package]
name = "quake-map"
version = "0.1.0"
edition = "2024"

[dependencies]
quake-collision = { path = "../quake-collision" }
quake-resource = { path = "../quake-resource" }

anyhow.workspace = true
byteorder.workspace = true
glam.workspace = true

slotmap = "1.0.7"
nom = "8.0.0"
